-- =====================================================
-- SISTEMA DE PUNTO DE VENTA - LIBRERÍA
-- Versión: Final con Clientes y Múltiples Precios
-- Motor: PostgreSQL
-- =====================================================

-- 1. ENUMS
CREATE TYPE estado_sesion_enum AS ENUM ('Abierta', 'Cerrada');
CREATE TYPE metodo_pago_enum AS ENUM ('Efectivo', 'Tarjeta', 'Mixto'); 
CREATE TYPE estado_venta_enum AS ENUM ('Completada', 'Anulada');
CREATE TYPE nivel_precio_enum AS ENUM ('Publico', 'Mayorista', 'Costo');

-- 2. CATÁLOGOS BASE

CREATE TABLE Roles (
    rol_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE, 
    descripcion TEXT
);

CREATE TABLE Categorias (
    categoria_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE, 
    descripcion TEXT
);

CREATE TABLE Ubicaciones (
    ubicacion_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_corto VARCHAR(50) NOT NULL UNIQUE, 
    descripcion TEXT NOT NULL 
);

CREATE TABLE Proveedores (
    proveedor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_empresa VARCHAR(150) NOT NULL,
    nombre_contacto VARCHAR(100),
    telefono VARCHAR(20),
    email VARCHAR(100),
    nit_proveedor VARCHAR(30)
);

-- 3. CLIENTES
CREATE TABLE Clientes (
    cliente_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(150) NOT NULL,
    nit VARCHAR(20) DEFAULT 'CF',
    telefono VARCHAR(20),
    direccion TEXT,
    email VARCHAR(100),
    nivel_precio_asignado nivel_precio_enum NOT NULL DEFAULT 'Publico',
    activo BOOLEAN DEFAULT TRUE
);

-- 4. USUARIOS Y PRODUCTOS

CREATE TABLE Usuarios (
    usuario_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_id INT NOT NULL,
    nombre_completo VARCHAR(150) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (rol_id) REFERENCES Roles(rol_id)
);

CREATE TABLE Productos (
    producto_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id INT NOT NULL,
    ubicacion_id INT NOT NULL,
    nombre VARCHAR(150) NOT NULL, 
    descripcion TEXT,
    sku VARCHAR(100) UNIQUE,
    precio_venta DECIMAL(10, 2) NOT NULL CHECK (precio_venta >= 0),
    precio_mayorista DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    precio_costo DECIMAL(10, 2) DEFAULT 0.00,
    cantidad_stock INT NOT NULL DEFAULT 0,
    activo BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (categoria_id) REFERENCES Categorias(categoria_id),
    FOREIGN KEY (ubicacion_id) REFERENCES Ubicaciones(ubicacion_id)
);

-- 5. COMPRAS

CREATE TABLE Compras (
    compra_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id INT NOT NULL,
    usuario_id INT NOT NULL,
    fecha_compra DATE NOT NULL DEFAULT CURRENT_DATE,
    numero_factura_proveedor VARCHAR(100),
    total_compra DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (proveedor_id) REFERENCES Proveedores(proveedor_id),
    FOREIGN KEY (usuario_id) REFERENCES Usuarios(usuario_id)
);

CREATE TABLE Detalle_Compras (
    detalle_compra_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id INT NOT NULL,
    producto_id INT NOT NULL,
    cantidad INT NOT NULL,
    precio_costo_compra DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (compra_id) REFERENCES Compras(compra_id) ON DELETE CASCADE,
    FOREIGN KEY (producto_id) REFERENCES Productos(producto_id)
);

-- 6. VENTAS

CREATE TABLE Sesiones_Caja (
    sesion_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_apertura_id INT NOT NULL,
    fecha_apertura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    monto_inicial DECIMAL(10, 2) NOT NULL,
    usuario_cierre_id INT NULL, 
    fecha_cierre TIMESTAMP NULL,
    monto_final_esperado DECIMAL(10, 2) NULL,
    monto_final_contado DECIMAL(10, 2) NULL,
    diferencia DECIMAL(10, 2) NULL,
    estado estado_sesion_enum NOT NULL DEFAULT 'Abierta',
    FOREIGN KEY (usuario_apertura_id) REFERENCES Usuarios(usuario_id),
    FOREIGN KEY (usuario_cierre_id) REFERENCES Usuarios(usuario_id)
);

CREATE TABLE Ventas (
    venta_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesion_id INT NOT NULL,
    usuario_id INT NOT NULL,
    cliente_id INT NOT NULL,
    fecha_venta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    monto_total DECIMAL(10, 2) NOT NULL,
    metodo_pago metodo_pago_enum NOT NULL DEFAULT 'Efectivo',
    estado estado_venta_enum NOT NULL DEFAULT 'Completada',
    motivo_anulacion TEXT NULL,
    fecha_anulacion TIMESTAMP NULL,
    usuario_anulo_id INT NULL,
    FOREIGN KEY (sesion_id) REFERENCES Sesiones_Caja(sesion_id),
    FOREIGN KEY (usuario_id) REFERENCES Usuarios(usuario_id),
    FOREIGN KEY (usuario_anulo_id) REFERENCES Usuarios(usuario_id),
    FOREIGN KEY (cliente_id) REFERENCES Clientes(cliente_id)
);

CREATE TABLE Detalle_Ventas (
    detalle_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id INT NOT NULL,
    producto_id INT NOT NULL,
    cantidad INT NOT NULL,
    precio_unitario DECIMAL(10, 2) NOT NULL, 
    descuento DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    subtotal DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (venta_id) REFERENCES Ventas(venta_id) ON DELETE CASCADE,
    FOREIGN KEY (producto_id) REFERENCES Productos(producto_id)
);

CREATE TABLE Ajustes_Inventario (
    ajuste_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT NOT NULL,
    producto_id INT NOT NULL,
    fecha_ajuste TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    cantidad INT NOT NULL, 
    motivo VARCHAR(200) NOT NULL, 
    FOREIGN KEY (usuario_id) REFERENCES Usuarios(usuario_id),
    FOREIGN KEY (producto_id) REFERENCES Productos(producto_id)
);

-- AUDIT LOGS (Si aplica)
CREATE TABLE IF NOT EXISTS audit_logs (
    audit_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT,
    accion VARCHAR(50) NOT NULL,
    entidad VARCHAR(50) NOT NULL,
    entidad_id INT,
    detalles TEXT,
    fecha_accion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45)
);

-- =====================================================
-- DATOS SEMILLA (SEEDS)
-- =====================================================

INSERT INTO Roles (nombre, descripcion) VALUES 
('Administrador', 'Acceso total y configuración'),
('Vendedor', 'Punto de venta y consultas');

INSERT INTO Ubicaciones (nombre_corto, descripcion) VALUES ('GEN', 'Ubicación General');
INSERT INTO Categorias (nombre, descripcion) VALUES ('General', 'Productos varios');
INSERT INTO Clientes (nombre_completo, nivel_precio_asignado) VALUES ('Consumidor Final', 'Publico');

INSERT INTO Usuarios (rol_id, nombre_completo, username, password_hash) 
VALUES (
    1, 
    'Super Admin', 
    'administradorLB', 
    '$2a$12$bMQUVtO3cA6g17SeTRDyn.vNcXJNEWxSSHo3lH/A0Om/KVHM0Ifyi'
);
